### ISSUE TITLE
Feature request: a special way to generate frame genesis

### ISSUE THREAD

**Issue by jeffgyf** [Kahsolt/stable-diffusion-webui-prompt-travel#11]
Found a special way to generate frame genesis, hopefully it can be implemented in this extension.
![image](https://user-images.githubusercontent.com/16674327/212546306-bc259e78-1950-42ec-8806-0eef32b2e5fc.png)
https://replicate.com/andreasjansson/stable-diffusion-animation

**Comment by Kahsolt** [comment]
Brilliant! Nice smooth animation!! I will try to reproduce it!!! 😃

**Comment by Kahsolt** [comment]
This seems somewhat alike current prompt-travel implementation in `Img2Img` pipeline with `fixed` genesis. 
Might there still be some difference, I will examine it in details tomorrow :)

**Comment by Kahsolt** [comment]
Hello~ This feature is available now. 
Though I've followed this [guide](https://replicate.com/andreasjansson/stable-diffusion-animation#readme) exactly, the output smoothness is still not that satisfying. I finally owe it to the FILM model, rather than its novel genesis strategy that dramatically improves the video smoothness ;)
