### ISSUE TITLE
"Hires. fix" doesn't work with successive or embryo frame genesis methods

### ISSUE THREAD

**Issue by hcorion** [Kahsolt/stable-diffusion-webui-prompt-travel#15]
With embryo I get the error "the save of tensor a (40) must match the size of sensor b"
and with successive only the first frame is generated all full resolution, subsequent frames don't get the hires treatment.

**Comment by Kahsolt** [comment]
Hi~ I found that this script will not probably work together with `hires.fix`, due to some inner conceptual/logical conflict of `denoising_strength`, you can alternatively perform batch-upscale then batch-img2img.  

![image](https://user-images.githubusercontent.com/22111194/215943074-7749833c-c977-4c38-b087-9cc44ad20cb2.png)

Traveling requires a large `denoising_strength` to change contents, moving forward. However, successive mode with hires.fix is equivalent to do img2img on **high resolution images** with relative high `denoising_strength`, it performs bad because models are typically trained on **low resolution images**.
