### ISSUE TITLE
Feature request: ability to supply a depth map

### ISSUE THREAD

**Issue by enn-nafnlaus** [Kahsolt/stable-diffusion-webui-prompt-travel#16]
See the "Custom depth images" script for an example.  It's a shame that one can't both provide a custom depth map, and run prompt travel, at the same time.

**Comment by Kahsolt** [comment]
thx for the suggestion, I guess that you are working with the img2img pipeline?
When img2img, use that "Inpaint upload" instead of ”img2img" will literally do the travelng with one given mask.
For txt2img, I could not find an understandable reason to use mask, since the generated content is almost unpredictable.

btw, I'm not quite familiar with that "Custom depth images" script, do you mean [this](https://github.com/AnonymousCervine/depth-image-io-for-SDWebui) or something else? Any links please?
btw again, ptravel mainly works for txt2img, performance is generally worse in img2img (it more like a seed_travel under img2img

**Comment by enn-nafnlaus** [comment]
Thanks for the response  :)  No, I'm working with txt2img.

Yes, that's the extension.  It should make it clear how they pull it off.  Unfortunately I can't run that script and yours at the same time, as you can only run one script at once!

Custom depth maps let you pull off stuff like this:

![image](https://user-images.githubusercontent.com/116288799/218433997-49fb28d4-ed66-48c1-8c54-4eba8859c581.png)

![image](https://user-images.githubusercontent.com/116288799/218434038-bf0d64c0-c841-45d2-bf96-14cec5c0e80c.png)

![image](https://user-images.githubusercontent.com/116288799/218434089-c9e59817-0a58-42ba-998a-0c9a33a6d2c7.png)

Being able to prompt travel, but with a custom depth map, should make some really neat effects!

**Comment by Kahsolt** [comment]
🆗 I've got the idea , but it seems to be some new functionality from SD2...? 
Where could I get a depth2img model ckpt for the development & test?
So that I could add the very basic feature that `depth-image-io-for-SDWebui` does.

**Comment by enn-nafnlaus** [comment]
The depth2img checkpoint is here:

https://huggingface.co/stabilityai/stable-diffusion-2-depth/tree/main

**Comment by Kahsolt** [comment]
Nice, I'll make it

**Comment by enn-nafnlaus** [comment]
Awesome!  :)

**Comment by enn-nafnlaus** [comment]
Awesome!!!
