### ISSUE TITLE
AttributeError: 'ScriptRunner' object has no attribute 'before_process_batch'

### ISSUE THREAD

**Issue by skabbit** [Kahsolt/stable-diffusion-webui-prompt-travel#19]
The last commit for the WebUI extension now produces an error:
```
AttributeError: 'ScriptRunner' object has no attribute 'before_process_batch'
```

I suppose it is related to compatibility with the WebUI version v1.9.

**Comment by Kahsolt** [comment]
This script hook `before_process_batch` has been introduced into webui core since https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/a2d635ad135241a0a40f67f7e1638c9c8a4ded04 (dated back 02/22), could you just update your webui? 
I have no idea about webui's version strings, since it keeps rolling update, what is the `v1.9`?

**Comment by VisualBoy** [comment]
Same problem here, latest update broke it :(

**Comment by Kahsolt** [comment]
As I mentioned above, this `before_process_batch` commit has been merged into webui core for weeks. The latest ptravel also added it in and work on my machine :) This hook might be used for some other extensions, though ptravel itself does not use it.

For those guys still gets in trouble or reluctant to update webui due to some reason, I pushed a compatible fix, it should temporarily work for you ;)
