### ISSUE TITLE
Feature Request: RIFE implementation

### ISSUE THREAD

**Issue by marcsyp** [Kahsolt/stable-diffusion-webui-prompt-travel#24]
I love Prompt Travel and it works quite well, in some ways better than Seed Travel.  That said, there is one thing that Seed Travel has implemented that is very very nice -- and that is the RIFE passes for creating interpolated frames to smooth the animation results.  

I wonder if it is possible to implement RIFE passes for Prompt Travel (and eventually ControlNet Travel) in the same way that the Seed Travel project has done, it will make very smooth animations with Prompt Travel possible.  Thanks for your consideration!

**Comment by Kahsolt** [comment]
Well, RIFE has already long been a part of the Prompt Travel in its post-processing pipeline (we adopt a vulkan-ncnn distro rather than the pytorch versions). However you need to follow the extra installation steps in README.md, and it works offline the webui.

btw, I've integrated RIFE to ControlNet Travel today, but not ready to push due to some bugs respecting to controlnet.
but, RIFE would not be integrated in Prompt Travel, due to some inner logical.
