### ISSUE TITLE
Issue: controlnet-travel: controlnet preprocessor images are included in the video file

### ISSUE THREAD

**Issue by MoreColors123** [Kahsolt/stable-diffusion-webui-prompt-travel#27]
Thanks for that awesome and easy to use controlnet-script, I just realized it existed! As it says in the title, the black&white preprocessor-images are included in the resulting mp4 file (in between the actual frames). The results otherwise are really good though!

**Comment by Kahsolt** [comment]
🤔 Could you show me your `<output>` folder layout? 
It seems you are using a customized layout or naming template so that the preprocessed things got messed with target frames...?
And, is your video the direct output or after postprocessing?

**Comment by MoreColors123** [comment]
I am using the vladmandic repo which surely has a different folder structure:
![grafik](https://user-images.githubusercontent.com/131474336/235445441-909a945c-242a-418a-aeff-926b90ff6a4c.png)
![grafik](https://user-images.githubusercontent.com/131474336/235445482-877bd392-b312-4020-b345-dd00ad497ea8.png)

Don't know if you can solve that. Thanks anyway!

**Comment by Kahsolt** [comment]
Oh I got it.
To avoid this, you need switching on "Do not append detectmap to output" in "Setting - ControlNet", because ctravel did not find an elegant way to tell which image is a preprocessed scaffold and should be auto dropped :(

If you are annoyed to toggle this option again and again (for some certain possible workflow), you could use the post-processing toolkit (i.e. the `manager.py`) to compose again all frames via installed ffmpeg, overwriting the raw output.
