### ISSUE TITLE
IndexError: list index out of range ( RIFE )

### ISSUE THREAD

**Issue by mazz3d** [Kahsolt/stable-diffusion-webui-prompt-travel#33]
Hello
I have been trying for days to obtain the RIFE video from "Prompt Travel," but I have been unable to find it. It seems to be available only through "Controlnet Travel.
![Screenshot 2023-07-03 23491s7](https://github.com/Kahsolt/stable-diffusion-webui-prompt-travel/assets/80547063/4b829b19-fac4-40b8-b13e-dad6c5ca4bd3)
I encountered an error while attempting to create a video using prompts for RIFE interpolation. Is there any method or alternative way to generate a video with RIFE interpolation from prompts?

**Comment by Kahsolt** [comment]
👉 You just please use the extensive script `manager.py` for RIFE interpolation. 👈
To specify this, RIFE **mainly** works in the post-processing pipeline, in an offline sd-webui way; read also thread #20.

ps. Though the ControlNet-Travel script embeds part of the RIFE functionality within the sd-webui app, it offers an implementaion to interpolate on the input conditions (the canny/depth/..etc hint tensors) rather than the output frames, so probably not working in the way you currently understand :)

As for the `IndexError`, please show me more console logs and traceback info so that I can infer what is wrong.

**Comment by mazz3d** [comment]
> `manager.py` for RIFE interpolation

Thank you for your quick reply
yes, exactly I need it to be offline to have fewer rendering frames (I will rely on RIFE to get a longer video with fewer render time frames ) 
how to get or use the manager.py file, please is it inside the Travel prompt? would be really appreciated.

sure here are the errors 
![Screenshot 2023-07-04 105441](https://github.com/Kahsolt/stable-diffusion-webui-prompt-travel/assets/80547063/3d12739e-8d9b-43d2-ae5f-d5906017b28b)
![Screenshot 2023-07-04 105836](https://github.com/Kahsolt/stable-diffusion-webui-prompt-travel/assets/80547063/830f5139-3b73-4c07-b703-bdd3c50a6574)

**Comment by Kahsolt** [comment]
Of course this `manager.py` script is put right under the root folder of this extension, but you'd better run it with `manager.cmd` if using Windows.
Please be patient to read the section `#Post-processing pipeline` in `README.md`, though I know that it's getting somewhat tl;dr :(

Sadly this `controlnet-travel` is temporarily broken, since `sd-webui-controlnet` is updating rapidly. 
But I'm right now re-implementing it in a new way. And will notify the well-tested compatible version strings if `sd-webui` and `sd-webui-controlnet` in README :)

**Comment by Kahsolt** [comment]
ControlNet-Travel should be reworking now inv3.0, have a try bro~ :)
