### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by mazz3d** [Kahsolt/stable-diffusion-webui-prompt-travel#34]
Hello! Is anyone else experiencing errors when using the script with SDXL 0.9?
![image](https://github.com/Kahsolt/stable-diffusion-webui-prompt-travel/assets/80547063/46012b13-0d8c-40d0-a3d3-a506c2fd5ac0)
 I've been having a great time creating videos using Prompts Travel in the 2.1 models.

**Comment by Kahsolt** [comment]
I'm not familiar with SDXL 0.9, even don't know if ptravel will work with the 2.1 models.... :lol

But I've search the class name `DictWithShape` in the sd-webui repo (I'm on A1111's stream) and found nothing.
It seems to need extra code support to run this `SDXL 0.9`?

If I'm able to get these stuff in your env, maybe I could help to support this. Point me away please?

**Comment by mazz3d** [comment]
Yes, it works wonderfully with the 2.1 models. The transition from one prompt to the next is incredibly smooth. 💯 :)
sorry what do you mean of _(If I'm able to get these stuff in your env, maybe I could help to support this. Point me away please?)_
id love to help if I could

**Comment by Kahsolt** [comment]
Nice!! Feel relieved that this extension could outputs something meaningful :)
And sorry for the late reply, there's some time lap due to the timezone.

I mean to support this `SDXL ?.?`, I need to reproduce the error you've just got in my develop env.
So please tell me what the checkpoint file you actually use, where can I get it.
And what the necessary extensions you activate in order to run this SDXL (if there's any)

**Comment by mazz3d** [comment]
> Nice!! Feel relieved that this extension could outputs something meaningful :) And sorry for the late reply, there's some time lap due to the timezone.
> 
> I mean to support this `SDXL ?.?`, I need to reproduce the error you've just got in my develop env. So please tell me what the checkpoint file you actually use, where can I get it. And what the necessary extensions you activate in order to run this SDXL (if there's any)

Hi, I apologize for the delayed response. I just noticed your reply now :D
I was referring to SDXL 0.9, the latest update of SD.
Here are some screenshots that might be helpful.
![image](https://github.com/Kahsolt/stable-diffusion-webui-prompt-travel/assets/80547063/5ff34dd1-1584-4c8b-8180-1312511da4e9)
![image](https://github.com/Kahsolt/stable-diffusion-webui-prompt-travel/assets/80547063/c7fc72b4-f3a3-457f-add8-e14e84e9aa3c)
![image](https://github.com/Kahsolt/stable-diffusion-webui-prompt-travel/assets/80547063/4ee6f096-ea07-4ebc-b295-9c89f2ca91c9)
I hope this information proves helpful.

**Comment by Kahsolt** [comment]
Yes, enough, thx. I'll check it next week as soon as possible.
Currently busy with a coding competition :)

**Comment by Kahsolt** [comment]
Latest news, I've just downloaded the SDXL 1.0 and starting to code :)
Two days later should be available.

**Comment by Kahsolt** [comment]
Now ready for SDXL v1.0 model, please try `v3.1`~

I've run few examples to find that the generated frames are not that consecutive like those v1.4 models.
This might be due to the text encoder (CLIP) in `SDXL v1.0` has a much higher dimension 2048, contrasted with 768 in legacy models, so more information could be compressed into the model, but subtle change of input params could lead to a jump in the outputs :(

Please have a try and report the performance~
